version: '3.4'
volumes:
    redis: ~
services:
    php:
        build:
            context: .
            target: build_php
            dockerfile: ./docker/Dockerfile
            args:
                DUMP_ENV: 1
        hostname: php
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
    apache:
        build:
            context: .
            target: build_apache
            dockerfile: ./docker/Dockerfile
        hostname: apache
        environment:
            PHP_HANDLER_HOST: php:9000
    mysql:
        image: mysql:5.7
        hostname: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
    redis:
        image: bitnami/redis:5.0.5-debian-9-r56
        hostname: redis
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        volumes:
            - redis:/data
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
    smtp:
        image: namshi/smtp
