version: '3.5'
services:
    php:
        image: fleet-manager-spa-php:latest
        hostname: php
        depends_on:
            - redis
    apache:
        image: fleet-manager-spa-apache:latest
        hostname: apache
        environment:
            PHP_HANDLER_HOST: php:9000
        depends_on:
            - php
    redis:
        image: bitnami/redis:5.0.5-debian-9-r56
        hostname: redis
